// Génère agiloshield-v2-icons.js depuis le coffre Nucleo UI (licence Agilotext, hors repo).
// Usage : node tests/build-icons.mjs [chemin coffre ui-1.8.0]
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { homedir } from 'node:os';

const vault = process.argv[2] || join(homedir(), 'Documents/_DESIGN_ASSETS/Nucleo/packs/ui-1.8.0');
const ICONS = {
  'cloud-upload': 'outline/arrows/18px_cloud-upload.svg',
  'circle-question': 'outline/ui-layout/18px_circle-question.svg',
  'circle-check': 'outline/ui-layout/18px_circle-check.svg',
  'circle-warning': 'outline/ui-layout/18px_circle-warning.svg',
  'circle-info': 'outline/ui-layout/18px_circle-info.svg',
  dots: 'outline/ui-layout/18px_dots.svg',
  xmark: 'outline/ui-layout/18px_xmark.svg',
  check: 'outline/ui-layout/18px_check.svg',
  file: 'outline/files/18px_file.svg',
  text: 'outline/editing/18px_text.svg',
  key: 'outline/security/18px_key.svg',
  'shield-check': 'outline/security/18px_shield-check.svg',
  eye: 'outline/ui-layout/18px_eye.svg',
  'eye-slash': 'outline/ui-layout/18px_eye-slash.svg',
  download: 'outline/arrows/18px_download.svg',
  trash: 'outline/ui-layout/18px_trash.svg',
  clock: 'outline/time/18px_clock.svg',
  'select-area': 'outline/design-development/18px_select-area.svg',
  'split-view': 'outline/ui-layout/18px_split-view.svg',
  'magnifier-plus': 'outline/filtering-sorting/18px_magnifier-plus.svg',
  'magnifier-minus': 'outline/filtering-sorting/18px_magnifier-minus.svg',
  'arrow-left': 'outline/arrows/18px_arrow-left.svg',
  'arrow-right': 'outline/arrows/18px_arrow-right.svg',
};

const out = {};
for (const [name, rel] of Object.entries(ICONS)) {
  const svg = await readFile(join(vault, rel), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
    .replace(/\s*data-[a-z-]+="[^"]*"/g, '')
    .replace(/(stroke|fill)="(#000|black|#000000)"/g, '$1="currentColor"')
    .replace(/>\s+</g, '><').trim();
  out[name] = inner;
}

const body = `/* Nucleo UI icons © Nucleo, used under Agilotext's commercial license. Generated by tests/build-icons.mjs. */
export const ICONS = ${JSON.stringify(out, null, 0).replace(/","/g, '",\n"')};
export function iconSvg(name, size = 18) {
  const inner = ICONS[name];
  if (!inner) return '';
  return '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size + '" viewBox="0 0 18 18" aria-hidden="true" focusable="false">' + inner + '</svg>';
}
`;
const target = new URL('../agiloshield-v2-icons.js', import.meta.url);
await writeFile(target, body);
console.log('icons:', Object.keys(out).length, '->', target.pathname);
